version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres_db_persons
    restart: always
    environment:
      POSTGRES_DB: db_persons
      POSTGRES_USER: username
      POSTGRES_PASSWORD: supercontraseñasecreta
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/create_tables_script.sql:/docker-entrypoint-initdb.d/create_tables_script.sql

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
